branch-defaults:
  default:
    environment: jgrindalludacity-dev
  master:
    environment: jgrindalludacity-dev

deploy:
  artifact: archive.zip

global:
  application_name: jgrindalludacity
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  profile: deploy-cli
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application


