version: 2.1

orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0

workflows:
  build_and_test:
    jobs:
      - build


jobs:
   build:
      docker:
        - image: "cimg/base:stable"
      steps:
        - node/install
        - checkout
        - aws-cli/setup:
              profile-name: deploy-cli
        - run:
              name: hello
              command: |
                  echo "hello-world"
                      
        
                  
                  
        - run:
              name: serverinstall
              command: |
                  npm run server:install
                  
        - run:
              name: serverbuild
              command: |
                  npm run server:build
                  
                  
        - run:
              name: serverdeploy
              command: |
                  npm run server:deploy_aws