version: 2.1

orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@1.3.1

workflows:
  sample: # This is the name of the workflow,
    jobs:
    
      build:
        docker:
            - image: "cimg/base:stable"
        steps:
            - node/install
            - checkout
            - run:
                  name: hello
                  command: |
                      echo "hello-world"
                      
