#!/bin/bash

eb setenv BCRYPT_PASSWORD=BCRYPT_PASSWORD JWT_TOKEN_SECRET=JWT_TOKEN_SECRET POSTGRES_DB=POSTGRES_DB POSTGRES_HOST=POSTGRES_HOST POSTGRES_PASSWORD=POSTGRES_PASSWORD POSTGRES_USER=POSTGRES_USER SALT_ROUNDS=SALT_ROUNDS -e jgrindalludacity-dev --profile deploy-cli

eb deploy jgrindalludacity-dev --profile deploy-cli
